"""Restructure

Revision ID: 2b96276280a2
Revises: 
Create Date: 2025-12-13 23:47:38.276915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b96276280a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=50), nullable=True),
    sa.Column('relation_to_admin', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('pic_path', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('project_title', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('fund_amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('project_site', sa.String(length=50), nullable=False),
    sa.Column('project_partners', sa.String(length=50), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('system_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_change', sa.String(length=50), nullable=True),
    sa.Column('details', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('admin_votes',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(length=10), nullable=False),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.request_id'], ),
    sa.PrimaryKeyConstraint('vote_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('given_fund', sa.Float(), nullable=False),
    sa.Column('approval_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.request_id'], ),
    sa.PrimaryKeyConstraint('project_id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('project_updates',
    sa.Column('update_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('posted_by', sa.Integer(), nullable=False),
    sa.Column('update_title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('expenses', sa.Float(), nullable=False),
    sa.Column('receipt_picture', sa.String(length=50), nullable=True),
    sa.Column('site_picture', sa.String(length=50), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['posted_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('update_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_updates')
    op.drop_table('projects')
    op.drop_table('admin_votes')
    op.drop_table('system_logs')
    op.drop_table('requests')
    op.drop_table('users')
    # ### end Alembic commands ###
